version: "3.9"
services:
  gis_notebook:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    working_dir: /home
    volumes:
      - .././:/home/:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    ports:
      - "8888:8888"